# Generated by rust2rpm 25
%bcond_without check
%global debug_package %{nil}

%global crate testcontainers

Name:           rust-testcontainers
Version:        0.15.0
Release:        %autorelease
Summary:        Library for integration-testing against docker containers from within Rust

License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/testcontainers
Source:         %{crates_source}
Source1:        https://github.com/testcontainers/testcontainers-rs/raw/0.15/LICENSE-Apache-2.0
Source2:        https://github.com/testcontainers/testcontainers-rs/raw/0.15/LICENSE-MIT


BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
A library for integration-testing against docker containers from within
Rust.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-Apache-2.0
%license %{crate_instdir}/LICENSE-MIT
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+async-trait-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+async-trait-devel %{_description}

This package contains library source intended for building other packages which
use the "async-trait" feature of the "%{crate}" crate.

%files       -n %{name}+async-trait-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+bollard-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+bollard-devel %{_description}

This package contains library source intended for building other packages which
use the "bollard" feature of the "%{crate}" crate.

%files       -n %{name}+bollard-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+conquer-once-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+conquer-once-devel %{_description}

This package contains library source intended for building other packages which
use the "conquer-once" feature of the "%{crate}" crate.

%files       -n %{name}+conquer-once-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+experimental-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+experimental-devel %{_description}

This package contains library source intended for building other packages which
use the "experimental" feature of the "%{crate}" crate.

%files       -n %{name}+experimental-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+signal-hook-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+signal-hook-devel %{_description}

This package contains library source intended for building other packages which
use the "signal-hook" feature of the "%{crate}" crate.

%files       -n %{name}+signal-hook-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tokio-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tokio-devel %{_description}

This package contains library source intended for building other packages which
use the "tokio" feature of the "%{crate}" crate.

%files       -n %{name}+tokio-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+watchdog-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+watchdog-devel %{_description}

This package contains library source intended for building other packages which
use the "watchdog" feature of the "%{crate}" crate.

%files       -n %{name}+watchdog-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep
cp -pv %{SOURCE1} %{SOURCE2} .

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
