# Generated by rust2rpm 25
%bcond_with check
%global debug_package %{nil}

%global crate spectral

Name:           rust-spectral
Version:        0.6.0
Release:        %autorelease
Summary:        Fluent test assertions

License:        Apache-2.0
URL:            https://crates.io/crates/spectral
Source:         %{crates_source}
# Manually created patch for downstream crate metadata changes
Patch:          spectral-fix-metadata.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Fluent test assertions.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+num-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+num-devel %{_description}

This package contains library source intended for building other packages which
use the "num" feature of the "%{crate}" crate.

%files       -n %{name}+num-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
